FQ25L008_GestContacts/Models/ErrorViewModel.cs
namespace FQ25L008_GestContacts.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FQ25L008_GestContacts/Models/Forms/CreateContactForm.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FQ25L008_GestContacts.Models.Forms
{
#nullable disable
    public class CreateContactForm
    {
        [Required]
        [MinLength(1)]
        [DisplayName("Nom : ")]
        public string Nom { get; set; }
        [Required]
        [MinLength(1)]
        [DisplayName("Prénom : ")]
        public string Prenom { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$")]
        [DisplayName("Adresse email : ")]        
        public string Email { get; set; }
        [DisplayName("Téléphone : ")]
        public string Tel { get; set; }
    }
}

FQ25L008_GestContacts/Models/Forms/UpdateContactForm.cs
using FQ25L008_GestContacts.Infrastructure.Validations;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FQ25L008_GestContacts.Models.Forms
{
    public class UpdateContactForm
    {
        [HiddenInput]
        public int Id { get; set; }

        [Required]
        [MinLength(1)]
        [DisplayName("Nom : ")]
        public string Nom { get; set; }
        [Required]
        [MinLength(1)]
        [DisplayName("Prénom : ")]
        public string Prenom { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$")]
        [UniqueEmail]
        [DisplayName("Adresse email : ")]
        public string Email { get; set; }
        [DisplayName("Téléphone : ")]
        public string? Tel { get; set; }
    }
}

FQ25L008_GestContacts/Controllers/ContactController.cs
using FQ25L008_GestContacts.Dal.Entities;
using FQ25L008_GestContacts.Dal.Repositories;
using FQ25L008_GestContacts.Models.Forms;
using Microsoft.AspNetCore.Mvc;


namespace FQ25L008_GestContacts.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactRepository _repository;

        public ContactController(IContactRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View(_repository.Get());
        }

        public IActionResult Details(int id)
        {
            Contact? contact = _repository.Get(id);

            if (contact is null)
            {
                return RedirectToAction("Index");
            }

            return View(contact);
        }

        //[HttpGet] // Http Verb Get
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // Http Verb Post
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateContactForm form)
        {
            if (!ModelState.IsValid)
            {
                return View(form);
            }

            //Insertion dans la DB
            _repository.Insert(new Contact() { Nom = form.Nom, Prenom = form.Prenom, Email = form.Email, Tel = form.Tel });
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Contact? contact = _repository.Get(id);

            if (contact is null)
            {
                return RedirectToAction("Index");
            }

            UpdateContactForm updateContactForm = new UpdateContactForm()
            {
                Id = contact.Id,
                Nom = contact.Nom,
                Prenom = contact.Prenom,
                Email = contact.Email,
                Tel = contact.Tel
            };

            return View(updateContactForm);
        }

        [HttpPost]
        public IActionResult Edit(int id, UpdateContactForm form)
        {
            if (!ModelState.IsValid)
            {
                return View(form);
            }

            // Update au niveau de la DB
            _repository.Update(new Contact() { Id = id, Nom = form.Nom, Prenom = form.Prenom, Email = form.Email, Tel = form.Tel });

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            Contact? contact = _repository.Get(id);
           
            if (contact is null)
            {
                return RedirectToAction("Index");
            }

            return View(contact);
        }

        [HttpPost]
        public IActionResult Delete(int id, IFormCollection form)
        {
            _repository.Delete(id);           

            return RedirectToAction("Index");
        }
    }
}

FQ25L008_GestContacts/Controllers/HomeController.cs
using System.Diagnostics;
using FQ25L008_GestContacts.Models;
using Microsoft.AspNetCore.Mvc;

namespace FQ25L008_GestContacts.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FQ25L008_GestContacts/Views/Contact/Create.cshtml
@model CreateContactForm

@{
    ViewData["Title"] = "Create";
}


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <hr />
            <div class="form-group">
                <input type="submit" value="Créer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FQ25L008_GestContacts/Views/Contact/Delete.cshtml
@model Contact

@{
    ViewData["Title"] = "Delete";
}

<h3>Êtes-vous sûre de vouloir supprimer cet élément ?</h3>
<div>
    <h4>Contact</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-info">Retour à la liste</a>        
    </form>
</div>

FQ25L008_GestContacts/Views/Contact/Details.cshtml
@model FQ25L008_GestContacts.Models.Contact

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Contact</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

FQ25L008_GestContacts/Views/Contact/Edit.cshtml
@model UpdateContactForm

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Contact</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FQ25L008_GestContacts/Views/Contact/Index.cshtml
@model IEnumerable<Contact>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.Nom
            </td>
            <td>
                @item.Prenom
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Détails</a> |
                <a asp-action="Edit" asp-route-id="@item.Id">Editer</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Supprimer</a>
            </td>
        </tr>
}
    </tbody>
</table>

FQ25L008_GestContacts/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <email mail-to="john.doe" user="John Doe"></email>
</div>

FQ25L008_GestContacts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FQ25L008_GestContacts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FQ25L008_GestContacts.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FQ25L008_GestContacts</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contacts</a>
                        </li>
                        @if(true) //si je suis admin
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Administration</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FQ25L008_GestContacts - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>